name: Fetch

on:
  schedule:
   - cron: '*/5 * * * *'

jobs:
  super-lint:
    name: Fetch snapshots
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download image
        uses: wei/curl@v1.1.1
        with:
          args: -o "imgs/$(date +"%Y%m%d%H%M%S").jpg" https://www.villaclara.it/images/webcam/webcam.php


      - name: Delete old files
        run: bash -c "git ls-tree -r --name-only HEAD imgs | while read filename; do if [ $(git log --follow --format=%at -- $filename | tail -1) -lt $(date -d 'yesterday' +%s) ]; then git rm $filename; fi; done;"
      #  uses: pkg-src/github-action-git-bash@v1.1
      #  with:
      #    args: "bash -c \"git ls-tree -r --name-only HEAD imgs | while read filename; do if [ $(git log --follow --format=%at -- $filename | tail -1) -lt $(date -d 'yesterday' +%s) ]; then git rm $filename; fi; done;\""
              
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add new snapshot
          commit_author: "action@github.com"
