name: Fetch

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  super-lint:
    name: Fetch snapshots
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download snapshot
        run: curl -o "imgs/$(date +'%Y-%m-%d %H:%M:%S').jpg" https://www.villaclara.it/images/webcam/webcam.php
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add new snapshot
          commit_author: "GitHub Actions <action@github.com>"

      - name: Delete old files
        run: tools/clean.sh        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Delete old snapshots
          commit_author: "GitHub Actions <action@github.com>"
