name: Timelapse

on: push

jobs:
  timelapse:
    name: Timelapse
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1-beta
      - run: ffmpeg -framerate 15 -pattern_type glob -i 'imgs/*.jpg' -c:v libx264 -pix_fmt yuv420p out.mp4 -y

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Create timelapse
