name: Timelapse

on:
  workflow_run:
    workflows: ["Fetch"]
    types:
      - completed

jobs:
  timelapse:
    name: Timelapse
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1-beta
      - run: ffmpeg -r 10 -pattern_type glob -i 'imgs/*.jpg' -vcodec libx264 out.mp4 -y

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Create timelapse
