name: Timelapse

on: push

jobs:
  timelapse:
    name: Timelapse
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1-beta
      - run: ffmpeg -framerate 30 -pattern_type glob -i '*.jpg' -vf crop=in_w:in_w*9/16,scale=1920:1080 -c:v libx264 -b:v 10000k -r 30 -pix_fmt yuv420p out.mp4

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Create timelapse
